### PR TITLE
make plugin compilable with newer grails

### PR DESCRIPTION
**Pull request by peh**
As grails now comes with groovy-2.4.7 and there have been changes to @CompileStatic between 2.4.5 and 2.4.7 there needed to be some minor adjustments to make it compilable with grails 3.2.x

### CODE REVIEW

**Comment by peh** [comment]
gorm 6 seems to case some trouble here. will fix

**Comment by puneetbehl** [comment]
Thanks @peh, I have manually merged your changes into 1.2.1, and now I am running all tests. Once everything is fine then I will release the same with 1.2.1

**Comment by peh** [comment]
still no release no?

**Comment by marcoscarceles** [comment]
Hi @puneetbehl @peh are these changes still compatible with Grails 3.1.x ? If not, we should bump version to 2.x.x instead of 1.2.1, since Grails 3.2 and grails 3.1 libraries are incompatible (eg. some core classes were moved to new packages)

**Comment by puneetbehl** [comment]
@marcoscarceles good point, let me verify this

**Pull request closed without merging**
