### PR TITLE
Migration alternatives

### LINKED ISSUE #64: Elasticsearch Merge Issues
Firstly, thank you for developing this plugin. It is very useful.

After upgrading to Elasticsearch plugin 0.0.3.6. We are getting merge exception, every-time we do run-app. This happens even when have disabled elasticsearch.index is disabled in bootstrap.groovy.

This is the case with plugin version 0.0.3.3

We are using:
Elastic Search Server 1.4.0
Grails 2.4.3
Tomcat Plugin build ":tomcat:8.0.14"

Settings in config.groovy
elasticSearch.datastoreImpl = 'mongoDatastore'
elasticSearch.client.mode = 'transport'
elasticSearch.bulkIndexOnStartup = false

Any pointers will be very helpful.

### PR DESCRIPTION
**Pull request by marcos-carceles**
Fixes #64 

Created multiple strategies for dealing with MergeMappingException:

- none : Keeps current behaviour
- delete: Deletes the mapping (therefore the documents of this type) and recreates the content during bootstrap
- alias: Creates a new version of the index <indexName>_v<VersionNumber> and creates the mappings there. How content is indexed on this case is managed by multiple configuration properties with sensible defaults. This implementation tries to accomplish these results: http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/

*In any case* two new aliases are created per every index, `<indexName>_read` and `<indexName>_write` used for querying and indexing content. These two aliases centralise the index where content is being read/written, which deals with conflicts on mappings on applications running multiple instances.

I believe tests on `test/integration/org/grails/plugins/elasticsearch/mapping/MappingMigrationSpec.groovy` and the grails docs should be descriptive enough for all scenarios, if not, please let me know and I'll be happy to amend.

### CODE REVIEW

**Comment by motleycrew** [comment]
Awesome job! When can we get this update? Thank you so much Marcos!

**Comment by noamt** [comment]
0.0.4.0 is released!
Thanks much, @marcos-carceles !
How would you like committer rights on the project?

**Comment by marcos-carceles** [comment]
thanks to you @noamt!
that'd be an honour :D

**Comment by sircelsiussexy** [comment]
Congrats @marcos-carceles, really nice work!

**Pull request merged**
