### PR TITLE
Ported to Grails 3

### PR DESCRIPTION
**Pull request by puneetbehl**
This version of plugin support Grails 3. I've update all the unit and integration tests. Please let me know if you have any issues or concerns.

### CODE REVIEW

**Comment by Schlogen** [comment]
@noamt Can you confirm whether or not you intend to merge this PR and release a Grails 3 version in the near future?

**Comment by noamt** [comment]
Sorry, I just have no more time to maintain this :(

**Comment by noamt** [comment]
I'll be happy to give anyone commit rights if they're up for it

**Comment by sbglasius** [comment]
If @puneetbehl wants to maintain it, I'm sure he is capable.

**Comment by puneetbehl** [comment]
@noamt  @sbglasius Sure, I am up for it.

**Comment by Schlogen** [comment]
@puneetbehl It seems like you left out including the default config in this PR

**Comment by puneetbehl** [comment]
@Schlogen  In Grails 3.x this default configuration can be migrated to grails-app/conf/application.yml and it will automatically be loaded by Grails without requiring manual configuration merging. 
Please read **Step 5 - Migrate Plugin Specific Config to application.yml** in following page [http://grails.github.io/grails-doc/latest/guide/upgrading.html#upgradingPlugins](http://grails.github.io/grails-doc/latest/guide/upgrading.html#upgradingPlugins)

**Comment by Schlogen** [comment]
@puneetbehl The `application.yml` file is only for running the plugin itself, tests, etc. In addition there are several configuration keys that won't work in a yml file (lists, maps, etc). If you include the plugin in a project you will see that no config exists during the `ElasticSearchGrailsPlugin.groovy` execution

**Comment by puneetbehl** [comment]
@noamt any updates?

**Comment by noamt** [comment]
I'll give you commit rights to the project, Puneet

**Comment by noamt** [comment]
Done. Thanks for your contributions!

**Pull request merged**
