### PR TITLE
Elasticsearch 2.1.2

### LINKED ISSUE #135: Support for Elasticsearch 2.x
Elasticsearch 2.x has been out and stable for some time. Are there any plans to add support for it?

### PR DESCRIPTION
**Pull request by marcoscarceles**
Fixes #135

### CODE REVIEW

**Comment by puneetbehl** [comment]
@marcoscarceles  Thanks for the help. It seems like there are lots of jars added in [183a03f](https://github.com/marcoscarceles/elasticsearch-grails-plugin/commit/183a03fce296944cea3f0eeaae8ea338e226b0f3) and I think that would make this repository heavy so could you please add a new commit to remove these or have alternate way.

**Comment by marcoscarceles** [comment]
Hi @puneetbehl , I'll have a look on finding a way to load them during the tests, but they need to be there in order to install the mapper-attachments plugin. These would go on a later version of ES (2.2.x). Also, can you provide some feedback on #141? Cheers!

**Comment by marcoscarceles** [comment]
@puneetbehl I removed the binaries on 50e7447, these are now downloaded during the test phase start

**Comment by marcoscarceles** [comment]
@puneetbehl @noamt would it be possible to release this the Grails repo? Would it be possible to get grails.org credentials, so I can publish new revisions to the grails-2.x version for future ES versions?

Cheers!

**Pull request merged**
