### PR TITLE
Added support for dynamic mapping of JSON String fields

### LINKED ISSUE #88: Support for dynamic type mapping
it would be super nice to have a mapping option to map string values dynamicly as of
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/dynamic-mapping.html

from time to time we use JSON object in String fields to store information we dont want to be database fields in mysql but it would be super cool to build elasticsearch queries for those "nested" objects

### PR DESCRIPTION
**Pull request by peh**
fixes #88

### CODE REVIEW

**Comment by noamt** [comment]
Thanks for this!
Can you please add some integration tests?

**Comment by peh** [comment]
added one that should cover the functionality

**Comment by noamt** [comment]
Cheers!

**Comment by peh** [comment]
should i add more or do you think this is enough?

**Comment by peh** [comment]
hey noam, can i add anything to make this merge happen?

**Comment by noamt** [comment]
I'll take care of it by the weekend

**Pull request merged**
